const baseUrl = 'https://cosmatics.growfet.com';
const loginEndpoint = "/api/Auth/login";
const registerEndpoint = '/api/Auth/register';
const countryCodesEndpoint = '/api/Countries';
const otpEndpoint = "/api/Auth/verify-otp";
const resendOtpEndpoint = "/api/Auth/resend-otp";
const sliderEndpoint = "/api/Sliders";
const categoriesEndpoint = "/api/Categories";
const productsEndpoint = "/api/Products";
const addToCartEndpoint = "/api/Cart/add";
const getCartEndpoint = "/api/Cart";
const deleteCartItemEndpoint = "/api/Cart/remove/";
const updateCartItemEndpoint = "/api/Cart/update";
const getProfileEndpoint = "/api/Auth/profile";
const updateProfileEndpoint = "/api/Auth/profile";
const forgetPasswordEndpoint = "/api/Auth/forgot-password";
const resetPasswordEndpoint = "/api/Auth/reset-password";
const logoutEndpoint = "/api/Auth/logout";
const skipOnboardingK = "skipOnboardingK";
const loadingImage = "assets/images/Loading.json";
const logedK = "loged";
const tokenK = "tokenK";
const latk = "latK";
late double? userLat;
late double? userLang;
late String? userAddress;
const longk = "longK";
const posK = "posK";
String? token;
